'use client'

import { useState, useEffect, useRef } from 'react'
import { useRouter } from 'next/navigation'
import { CheckSquare, CheckCircle, Syringe, Eye, X, Plus, Maximize2, Clock } from 'lucide-react'

interface TasksPanelProps {
  isOpen: boolean
  onClose: () => void
}

interface Task {
  id: string
  title: string
  dueDate: string
  isCompleted: boolean
  isAutoGenerated: boolean
  icon?: 'check' | 'syringe' | 'eye'
  dueDateColor?: 'red' | 'gray'
}

const initialTasks: Task[] = [
  {
    id: '1',
    title: 'Wean litter — Cage A-107',
    dueDate: 'Today',
    isCompleted: false,
    isAutoGenerated: true,
    icon: 'check',
    dueDateColor: 'red',
  },
  {
    id: '2',
    title: 'Tamoxifen — Group B animals',
    dueDate: 'Today',
    isCompleted: false,
    isAutoGenerated: true,
    icon: 'syringe',
    dueDateColor: 'red',
  },
  {
    id: '3',
    title: 'Weight check — Experiment 3',
    dueDate: 'Tomorrow',
    isCompleted: false,
    isAutoGenerated: true,
    icon: 'eye',
    dueDateColor: 'gray',
  },
  {
    id: '4',
    title: 'Review IACUC renewal',
    dueDate: 'May 30',
    isCompleted: false,
    isAutoGenerated: false,
  },
  {
    id: '5',
    title: 'Order new bedding supplies',
    dueDate: 'Jun 1',
    isCompleted: false,
    isAutoGenerated: false,
  },
]

export default function TasksPanel({ isOpen, onClose }: TasksPanelProps) {
  const router = useRouter()
  const panelRef = useRef<HTMLDivElement>(null)
  const [activeTab, setActiveTab] = useState<'today' | 'upcoming' | 'done'>('today')
  const [tasks, setTasks] = useState(initialTasks)
  const [isAddingTask, setIsAddingTask] = useState(false)
  const [newTaskTitle, setNewTaskTitle] = useState('')

  // Close on click outside
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (panelRef.current && !panelRef.current.contains(event.target as Node)) {
        onClose()
      }
    }

    if (isOpen) {
      document.addEventListener('mousedown', handleClickOutside)
    }

    return () => {
      document.removeEventListener('mousedown', handleClickOutside)
    }
  }, [isOpen, onClose])

  const handleOpenFullTasks = () => {
    router.push('/dashboard/tasks')
    onClose()
  }

  const handleAddTask = () => {
    setIsAddingTask(true)
  }

  const toggleTaskCompletion = (taskId: string) => {
    setTasks(prev =>
      prev.map(task =>
        task.id === taskId
          ? { ...task, isCompleted: !task.isCompleted }
          : task
      )
    )
  }

  const dismissTask = (taskId: string) => {
    setTasks(prev => prev.filter(task => task.id !== taskId))
  }

  const snoozeTask = (taskId: string) => {
    console.log('Snooze task:', taskId)
  }

  const addNewTask = () => {
    if (newTaskTitle.trim()) {
      const newTask: Task = {
        id: Date.now().toString(),
        title: newTaskTitle.trim(),
        dueDate: 'No due date',
        isCompleted: false,
        isAutoGenerated: false,
      }
      setTasks(prev => [...prev, newTask])
      setNewTaskTitle('')
      setIsAddingTask(false)
    }
  }

  const handleAddTaskKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
      addNewTask()
    } else if (e.key === 'Escape') {
      setIsAddingTask(false)
      setNewTaskTitle('')
    }
  }

  const getFilteredTasks = () => {
    switch (activeTab) {
      case 'today':
        return tasks.filter(t => !t.isCompleted && t.dueDate.includes('Today'))
      case 'upcoming':
        return tasks.filter(t => !t.isCompleted && !t.dueDate.includes('Today'))
      case 'done':
        return tasks.filter(t => t.isCompleted)
      default:
        return tasks
    }
  }

  const getTaskIcon = (task: Task) => {
    switch (task.icon) {
      case 'check':
        return <CheckCircle className="w-4 h-4" style={{ color: '#1A7F64' }} />
      case 'syringe':
        return <Syringe className="w-4 h-4" style={{ color: '#F5A623' }} />
      case 'eye':
        return <Eye className="w-4 h-4" style={{ color: '#6B7280' }} />
      default:
        return null
    }
  }

  const getDueBadgeStyle = (task: Task) => {
    if (task.dueDateColor === 'red') {
      return {
        backgroundColor: '#FCEBEB',
        color: '#A32D2D',
      }
    }
    return {
      backgroundColor: '#FEF3D8',
      color: '#854F0B',
    }
  }

  const filteredTasks = getFilteredTasks()
  const autoTasks = filteredTasks.filter(t => t.isAutoGenerated)
  const manualTasks = filteredTasks.filter(t => !t.isAutoGenerated)
  const todayTasksCount = tasks.filter(t => !t.isCompleted && t.dueDate.includes('Today')).length

  if (!isOpen) return null

  return (
    <div
      ref={panelRef}
      className="absolute top-12 right-0 bg-white border rounded-xl shadow-xl z-50 overflow-hidden"
      style={{
        width: '340px',
        borderColor: '#E2E8F0',
        maxHeight: '520px',
        boxShadow: '0 4px 24px rgba(0,0,0,0.12)'
      }}
    >
      {/* Header */}
      <div
        className="px-3 py-2.5 border-b flex items-center justify-between"
        style={{ borderColor: '#E2E8F0', height: '44px' }}
      >
        <h2 className="font-display font-medium" style={{ fontSize: '14px', color: '#1A1A2E' }}>
          Tasks & Reminders
        </h2>
        <div className="flex items-center space-x-2">
          <button
            onClick={handleAddTask}
            className="p-1 hover:text-primary transition-colors"
            title="Add task"
            style={{ color: '#9CA3AF' }}
          >
            <Plus className="w-3.5 h-3.5" />
          </button>
          <button
            onClick={handleOpenFullTasks}
            className="p-1 hover:text-primary transition-colors"
            title="Open full tasks view"
            style={{ color: '#9CA3AF' }}
          >
            <Maximize2 className="w-3.5 h-3.5" />
          </button>
          <button
            onClick={onClose}
            className="p-1 hover:text-red-500 transition-colors"
            style={{ color: '#9CA3AF' }}
          >
            <X className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex border-b" style={{ borderColor: '#E2E8F0', height: '36px' }}>
        {[
          { key: 'today', label: 'Today' },
          { key: 'upcoming', label: 'Upcoming' },
          { key: 'done', label: 'Done' },
        ].map((tab) => (
          <button
            key={tab.key}
            onClick={() => setActiveTab(tab.key as typeof activeTab)}
            className={`flex-1 px-3 text-xs font-medium transition-colors flex items-center justify-center ${
              activeTab === tab.key
                ? 'border-b-2 text-primary font-medium'
                : 'text-gray-500 hover:text-ink'
            }`}
            style={{
              fontSize: '12px',
              borderColor: activeTab === tab.key ? '#1A7F64' : 'transparent',
              color: activeTab === tab.key ? '#1A7F64' : '#6B7280',
            }}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* Add Task Input */}
      {isAddingTask && (
        <div className="px-3 py-2 border-b" style={{ borderColor: '#E2E8F0' }}>
          <input
            type="text"
            value={newTaskTitle}
            onChange={(e) => setNewTaskTitle(e.target.value)}
            onKeyDown={handleAddTaskKeyPress}
            placeholder="Add a task and press Enter..."
            className="w-full px-0 py-1 border-0 border-b focus:outline-none focus:ring-0"
            style={{
              borderColor: '#E2E8F0',
              fontSize: '13px',
              color: '#1A1A2E'
            }}
            autoFocus
          />
        </div>
      )}

      {/* Task Content */}
      <div className="max-h-80 overflow-y-auto">
        {filteredTasks.length > 0 ? (
          <>
            {/* Auto-generated tasks */}
            {autoTasks.length > 0 && (
              <>
                <div className="px-3 py-1.5" style={{ backgroundColor: '#F9FAFB' }}>
                  <h3
                    className="text-xs font-medium uppercase tracking-wider"
                    style={{ color: '#9CA3AF', fontSize: '10px' }}
                  >
                    FROM YOUR COLONY
                  </h3>
                </div>
                {autoTasks.map((task) => (
                  <TaskItem
                    key={task.id}
                    task={task}
                    onToggle={() => toggleTaskCompletion(task.id)}
                    onDismiss={() => dismissTask(task.id)}
                    onSnooze={() => snoozeTask(task.id)}
                    getTaskIcon={getTaskIcon}
                    getDueBadgeStyle={getDueBadgeStyle}
                  />
                ))}
              </>
            )}

            {/* Manual tasks */}
            {manualTasks.length > 0 && (
              <>
                {autoTasks.length > 0 && (
                  <div className="px-3 py-1.5" style={{ backgroundColor: '#F9FAFB' }}>
                    <h3
                      className="text-xs font-medium uppercase tracking-wider"
                      style={{ color: '#9CA3AF', fontSize: '10px' }}
                    >
                      MY TASKS
                    </h3>
                  </div>
                )}
                {manualTasks.map((task) => (
                  <TaskItem
                    key={task.id}
                    task={task}
                    onToggle={() => toggleTaskCompletion(task.id)}
                    onDismiss={() => dismissTask(task.id)}
                    onSnooze={() => snoozeTask(task.id)}
                    getTaskIcon={getTaskIcon}
                    getDueBadgeStyle={getDueBadgeStyle}
                  />
                ))}
              </>
            )}
          </>
        ) : (
          // Empty state
          <div className="flex flex-col items-center justify-center h-32 text-center px-4">
            <CheckCircle className="w-8 h-8 mb-3" style={{ color: '#9CA3AF' }} />
            <h3
              className="font-medium mb-1"
              style={{ fontSize: '14px', color: '#1A1A2E' }}
            >
              {activeTab === 'done' ? 'No completed tasks' : 'No tasks yet'}
            </h3>
            <p
              style={{ fontSize: '12px', color: '#6B7280' }}
            >
              {activeTab === 'done'
                ? 'Tasks you complete will appear here'
                : 'Add a task to get started'
              }
            </p>
          </div>
        )}
      </div>

      {/* Footer */}
      <div
        className="px-3 py-2 border-t text-center"
        style={{ borderColor: '#E2E8F0' }}
      >
        <span
          style={{ fontSize: '11px', color: '#6B7280' }}
        >
          {todayTasksCount} tasks due today
        </span>
      </div>
    </div>
  )
}

interface TaskItemProps {
  task: Task
  onToggle: () => void
  onDismiss: () => void
  onSnooze: () => void
  getTaskIcon: (task: Task) => React.ReactNode
  getDueBadgeStyle: (task: Task) => { backgroundColor: string; color: string }
}

function TaskItem({ task, onToggle, onDismiss, onSnooze, getTaskIcon, getDueBadgeStyle }: TaskItemProps) {
  return (
    <div
      className="group px-3 py-2 hover:bg-gray-25 transition-colors flex items-center space-x-2"
      style={{ borderColor: '#F9FAFB' }}
    >
      {/* Checkbox */}
      <button
        onClick={onToggle}
        className={`w-3.5 h-3.5 rounded border flex items-center justify-center transition-colors ${
          task.isCompleted
            ? 'bg-primary border-primary'
            : 'border-gray-300 hover:border-primary'
        }`}
        style={{
          borderColor: task.isCompleted ? '#1A7F64' : '#E2E8F0',
          backgroundColor: task.isCompleted ? '#1A7F64' : 'transparent',
        }}
      >
        {task.isCompleted && (
          <CheckSquare className="w-2 h-2 text-white" />
        )}
      </button>

      {/* Task Icon */}
      <div className="flex-shrink-0">
        {getTaskIcon(task)}
      </div>

      {/* Task Content */}
      <div className="flex-1 min-w-0">
        <div className="flex items-center space-x-2">
          <h3
            className={`font-medium line-clamp-1 ${
              task.isCompleted ? 'line-through opacity-60' : ''
            }`}
            style={{ fontSize: '13px', color: '#1A1A2E' }}
          >
            {task.title}
          </h3>
          {(task.dueDate === 'Today' || task.dueDate === 'Tomorrow') && (
            <span
              className="px-1.5 py-0.5 rounded text-xs font-medium"
              style={{
                ...getDueBadgeStyle(task),
                fontSize: '10px'
              }}
            >
              {task.dueDate}
            </span>
          )}
        </div>
        {task.dueDate !== 'Today' && task.dueDate !== 'Tomorrow' && (
          <p
            className={`text-xs ${task.isCompleted ? 'opacity-60' : ''}`}
            style={{ color: '#6B7280', fontSize: '11px' }}
          >
            {task.dueDate}
          </p>
        )}
      </div>

      {/* Hover Actions */}
      <div className="flex items-center space-x-1 opacity-0 group-hover:opacity-100 transition-opacity">
        <button
          onClick={onSnooze}
          className="w-5 h-5 rounded-full hover:bg-gray-100 flex items-center justify-center transition-colors"
          title="Snooze"
        >
          <Clock className="w-2.5 h-2.5 hover:text-amber transition-colors" style={{ color: '#9CA3AF' }} />
        </button>
        <button
          onClick={onDismiss}
          className="w-5 h-5 rounded-full hover:bg-gray-100 flex items-center justify-center transition-colors"
          title="Dismiss"
        >
          <X className="w-2.5 h-2.5 hover:text-red-500 transition-colors" style={{ color: '#9CA3AF' }} />
        </button>
      </div>
    </div>
  )
}